### ISSUE TITLE
Hard coded return value provides incorrect results back to markdown rendering

### ISSUE THREAD

**Issue by sheldonhull** [rnorth/mkdocs-codeinclude-plugin#21]
I really like this concept, as it is similar to the benefits of asciidoc `include` macro.
However, when I used this, I pointed to a file and it returned back a line at the beginning forcing the language, tab and not respecting the line break. 

```
    <!--codeinclude-->
    [register-compontents](./resources/_register_components.bat)
    <!--/codeinclude-->
```

```
	```java tab="register-compontents" @echo on @setlocal EnableDelayedExpansion
	```
```
In reviewing the [code](https://github.com/rnorth/mkdocs-codeinclude-plugin/blob/218dab87c402db6d5aae0dbd908408744bf5824f/codeinclude/plugin.py#L49) it seems to point towards a hard coded value being returned.

I hope to contribute a PR on this if I get a chance, but in the meantime, wanted to raise it as an issue so it can be tracked. 

Thanks!

**Comment by rnorth** [comment]
Hi @sheldonhull thanks! As you can probably tell, this plugin started out with a limited set of docs in mind for a Java project, hence being quite unhelpful in other contexts.

The good news is that @dmitry-timofeev has done a bunch of useful work, including adding language detection, so that language code blocks should be correctly marked now.

I've added an extra test case in #23 to illustrate, and will release a new version with this fixed soon.

All credit should go to @dmitry-timofeev for taking my crappy plugin and making it a lot better 😄

**Comment by sheldonhull** [comment]
This is great. I had just used a raw include template with indentation to help but wasn't the best solution at all. I look forward to trying this out!

**Comment by dmitry-timofeev** [comment]
Thanks @rnorth for your kind words! I really appreciate you open-sourcing the plugin and your work on it! It already was a strong plugin when I started 😄

**Comment by rnorth** [comment]
@sheldonhull for tidiness I'll close this issue now. Please feel free to re-open or file a related issue if you encounter any problems.
